langage: java
sudo: true
jdk: openjdk11

addons:
  sonnarcloud:
    organization: "ipseizangela"
    token: $SECRETVALUE

install:
  - mvn install -Dskiptests=test -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_deploy:
  - echo "done deploying"